Dev0.1
projeto-es-grupo-3/facilitai-backend pull request #18
Opened 2023-04-23 19:25 UTC by VANDRESSAGALDINOS

2023-04-23 19:57 UTC, pserey requested changes

2023-04-23 19:57 UTC, pserey commented on .idea/.gitignore
Adicionar  `.idea` no `.gitignore` para não commitar esses arquivos nos repositórios.

2023-04-23 19:57 UTC, pserey commented on src/routes.py
> +        abort(400, 'Matricula incorreta')
Quando o dado é mal formatado ou é de um tipo diferente é melhor usar a palavra "Inválida" do que "Incorreta".

2023-04-25 23:43 UTC, wendell-rafael approved these changes
tudo ok

2023-04-25 23:44 UTC, merged